/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_nativeclasses_NativeInterface */

#ifndef _Included_main_nativeclasses_NativeInterface
#define _Included_main_nativeclasses_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_nativeclasses_NativeInterface
 * Method:    getLong
 * Signature: ()J
 */

JNIEXPORT jlong JNICALL
Java_main_nativeclasses_NativeInterface_initFreeType(JNIEnv *env, jclass type);
#ifdef __cplusplus
}
#endif
#endif

