/* DO NOT EDIT THIS FILE - it is machine generated */


#ifndef HITBOX_H
#define HITBOX_H
#include <jni.h>

#ifdef __cplusplus
extern "C" {
#endif
    typedef struct hitbox
    {
        int32_t i16HalfSizeX;
        int32_t i16HalfSizeY;
        int16_t i16Top;
        int16_t i16Left;
        int16_t i16Bottom;
        int16_t i16Right;
        struct hitbox* pxHitboxNext;
    } Hitbox_t;

bool bHitboxIntersects(Hitbox_t *pxHitboxThis,
                       Hitbox_t *pxHitbox2);
void vHitboxUpdateEdges(Hitbox_t *pxHitbox1,
                        int16_t i16x,
                        int16_t i16y);
Hitbox_t* pxcollisionCheck(Hitbox_t* pxHitboxThis,
                           Hitbox_t* pxHitbox2);
#ifdef __cplusplus
}
#endif
#endif

